version: '{build}'
skip_tags: true
image: Visual Studio 2017
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start

    Nake.bat install

    Nake.bat package
test: off
artifacts:
- path: Output\**\*.nupkg