skip_tags: true

version: '{build}'

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - call "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
  - Nake.bat restore
  - Nake.bat package

test: off

artifacts:
- path: Output\Package\*.nupkg